#!/usr/bin/env bash
set -euo pipefail

if [ -z "${ZIG_GLOBAL_CACHE_DIR:-}" ]; then
	zig_global_cache_dir="$PWD/.zig-cache/global"
	export ZIG_GLOBAL_CACHE_DIR="$zig_global_cache_dir"
fi

zig build -j2 test bench fuzz
zig build -j2

SKIP_BUILD=1 ./tests/cli_test
